### ISSUE TITLE
Share container between xdist workers

### ISSUE THREAD

**Issue by thedrow** [praekeltfoundation/seaworthy#58]
Is it possible to share a container between xdist workers?
I'd like to perform an action instead of failing if the container already exists.

**Comment by jerith** [comment]
Unfortunately, pytest doesn't support sharing fixtures across xdist workers -- see https://github.com/pytest-dev/pytest/issues/252 for the relevant discussion.

When I looked at xdist and Seaworthy a while back, I couldn't find any solution to the problem of managing shared fixtures between processes. Even if we detect and handle fixture startup, there's no clean way to manage teardown and whichever worker removes it first will likely break any tests in other workers that still need it. (In order to have xdist work at all with more than one worker per host, we include the value of the `PYTEST_XDIST_WORKER` envvar in the fixture namespace to avoid conflicts.)

**Comment by elijahbal** [comment]
I can't believe you closed this issue.
This feature is absolutely crucial for keeping the pytest behaviour consistent. 

Currently, you are just breaking the expected pytest behaviour for most relevant use cases ('session' scoped fixture are really everywhere if you come to think of it).

The solution is quite simple: set up a master scheduler that will determine if a fixture has to be teared down or set up and just let the other workers wait for it.

I don't see how it could be difficult to implement such a thing.

**Comment by thedrow** [comment]
Well if pytest doesn't support it, it will be harder to implement.
if you have a solution I'd be happy if you shared it.

**Comment by jerith** [comment]
For clarification, session-scoped fixtures are completely supported within a single process (one global fixture when xdist isn't used, otherwise one fixture per xdist worker) which is exactly what pytest supports for all fixtures. (See the pytest issue linked above for the details.)

In addition, the fixture namespace used as a prefix for all docker entity names detects and includes the xdist worker identifier (if any) to avoid collisions between fixtures from different xdist workers on the same machine. This allows multiple xdist workers to coexist on a single host without fixture errors (at best) or unexpected and inconsistent test behaviour (at worst) as different workers tried to manage identically-named docker entities independently of each other.

**Comment by elijahbal** [comment]
Thank you for your answer. I was mistaken. I thought this was the direct project page of pytest-xdist.

Sorry for the inconvenience and thank you for your time while responding.
